name: Insert database

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Setup Node.js 14.x 
      uses: actions/setup-node@master
      with:
        node-version: "14.x"
    
    - name: Insert database
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        npm install commander mysql
        node /dbmaker/index.js --host $HOST --user $USER --password $PASSWORD
